name: Keep n8n Alive
on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping n8n Space
        run: curl https://shankiiii-my-n8n-tool.hf.space
